name: gymtracker
description: A new Flutter project.
publish_to: "none"
version: 0.13.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  animations: ^2.0.7
  copy_with_extension: ^5.0.0
  custom_refresh_indicator: ^3.1.0
  device_info_plus: ^10.1.0
  device_sim: ^0.1.2
  drift: ^2.16.0
  drift_db_viewer: ^2.0.0
  dynamic_color: ^1.6.2
  fast_noise: ^2.0.0
  file_picker: ^8.0.0+1
  fl_chart: ^0.68.0
  flat: ^0.5.0
  flex_color_picker: ^3.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^9.3.3
  flutter_slidable: ^3.1.2
  flutter_sticky_header: ^0.7.0
  flutter_timezone: ^1.0.8
  get: ^4.6.5
  intl: ^0.19.0
  json_annotation: ^4.8.0
  logger: ^2.2.0
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  protocol_handler: ^0.2.0
  qr_flutter: ^4.1.0
  quill_delta: ^3.0.0-nullsafety.2
  rxdart: ^0.27.7
  screenshot: ^3.0.0
  scrollable_clean_calendar: ^1.5.0
  share_plus: ^9.0.0
  simple_animations: ^5.0.2
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.20
  timezone: ^0.9.2
  universal_platform: ^1.0.0+1
  uuid: ^4.0.0

  drift_dev: any
  permission_handler: ^11.3.1
  flutter_markdown: ^0.7.2
  skeletonizer: ^1.3.0
  gauge_indicator: ^0.4.3
  easy_debounce: ^2.0.3
  openfoodfacts: ^3.11.0
  relative_time: ^5.0.0
  dio: ^5.4.3+1
  fuzzywuzzy: ^1.1.6
  collection: ^1.18.0
  flutter_zxing: ^1.7.0
  url_launcher: ^6.3.0
  sliver_tools: ^0.2.12
  csv: ^6.0.0
  flutter_svg: ^2.0.10+1
  xml: ^6.5.0
  rainbow_color: ^2.0.1
  audioplayers: ^6.1.0
  flex_color_scheme: ^8.0.0
  supabase_flutter: ^2.8.0
  pub_semver: ^2.1.4
  envied: ^0.5.4+1
  shared_preferences: ^2.3.3
  home_widget: ^0.7.0
  introduction_screen: ^3.1.14
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_quill_test: ^9.3.3
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.24.3
  flutter_gen_runner: ^5.8.0
  envied_generator: ^0.5.4+1
  pigeon: ^22.7.2

flutter_gen:
  assets:
    outputs:
      class_name: GTAssets
  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
        class_name: GTColors

flutter:
  fonts:
    - family: GymTracker
      fonts:
        - asset: fonts/GymTracker.ttf

  uses-material-design: true
  assets:
    - assets/audio/
    - assets/i18n/
    - assets/svg/
    - assets/svg/equipment/
    - assets/svg/trophies/
    #tool begin exercise-explanations
    - assets/exercises/abs/bicycleCrunches/
    - assets/exercises/abs/crunchMachine/
    - assets/exercises/abs/crunches/
    - assets/exercises/abs/deadBugHold/
    - assets/exercises/abs/deadBugHoldCardio/
    - assets/exercises/abs/extendedReverseCrunchWithLegExtension/
    - assets/exercises/abs/fullBodyCrunch/
    - assets/exercises/abs/heelTouches/
    - assets/exercises/abs/heelsUpCrunch/
    - assets/exercises/abs/hollowBodyHold/
    - assets/exercises/abs/hollowBodyHoldBentKnees/
    - assets/exercises/abs/kneeRaise/
    - assets/exercises/abs/legRaise/
    - assets/exercises/abs/plank/
    - assets/exercises/abs/russianTwist/
    - assets/exercises/abs/toeTouches/
    - assets/exercises/back/barbellRow/
    - assets/exercises/back/cableSeatedRowTriangleBar/
    - assets/exercises/back/deadlift/
    - assets/exercises/back/hyperExtensions/
    - assets/exercises/back/latPulldowns/
    - assets/exercises/back/pullUps/
    - assets/exercises/back/straightArmCablePushdown/
    - assets/exercises/back/triangleBarLatPulldowns/
    - assets/exercises/back/underhandGripLatPulldowns/
    - assets/exercises/back/weightedHyperExtensions/
    - assets/exercises/biceps/barbellBicepsCurl/
    - assets/exercises/biceps/bicepsCurlMachine/
    - assets/exercises/biceps/cableBicepsCurl/
    - assets/exercises/biceps/chinUps/
    - assets/exercises/biceps/concentrationCurl/
    - assets/exercises/biceps/dualCableHighCurl/
    - assets/exercises/biceps/dumbbellBicepsCurl/
    - assets/exercises/biceps/hammerCurlDumbbell/
    - assets/exercises/biceps/scottCurl/
    - assets/exercises/biceps/singleArmCableHammerCurls/
    - assets/exercises/biceps/spiderCurls/
    - assets/exercises/calves/calfPressLegPressMachine/
    - assets/exercises/calves/calfRaiseSeated/
    - assets/exercises/calves/calfRaiseStanding/
    - assets/exercises/cardio/aerobics/
    - assets/exercises/cardio/bicycleCrunchesCardio/
    - assets/exercises/cardio/biking/
    - assets/exercises/cardio/crunchesTimed/
    - assets/exercises/cardio/ergometer/
    - assets/exercises/cardio/ergometerHorizontal/
    - assets/exercises/cardio/jumpRope/
    - assets/exercises/cardio/pilates/
    - assets/exercises/cardio/rowingMachine/
    - assets/exercises/cardio/running/
    - assets/exercises/cardio/treadmill/
    - assets/exercises/cardio/zumba/
    - assets/exercises/chest/barbellBenchPressDecline/
    - assets/exercises/chest/barbellBenchPressFlat/
    - assets/exercises/chest/barbellBenchPressIncline/
    - assets/exercises/chest/butterflyMachine/
    - assets/exercises/chest/cableChestPress/
    - assets/exercises/chest/cableFlyCrossovers/
    - assets/exercises/chest/declinePushUps/
    - assets/exercises/chest/dumbbellBenchPressDecline/
    - assets/exercises/chest/dumbbellBenchPressFlat/
    - assets/exercises/chest/dumbbellBenchPressIncline/
    - assets/exercises/chest/dumbbellHexPress/
    - assets/exercises/chest/lowCableFly/
    - assets/exercises/chest/pushUps/
    - assets/exercises/chest/pushUpsWeighted/
    - assets/exercises/chest/seatedCableChestFlys/
    - assets/exercises/chest/smithMachineBenchPressDecline/
    - assets/exercises/chest/smithMachineBenchPressFlat/
    - assets/exercises/chest/smithMachineBenchPressIncline/
    - assets/exercises/chest/smithMachineHexPress/
    - assets/exercises/chest/verticalChestPress/
    - assets/exercises/forearms/farmerWalk/
    - assets/exercises/forearms/platePinch/
    - assets/exercises/forearms/reverseCurls/
    - assets/exercises/forearms/reverseWristCurlsBarbell/
    - assets/exercises/forearms/reverseWristCurlsDumbbell/
    - assets/exercises/forearms/wristCurlsBarbell/
    - assets/exercises/forearms/wristCurlsDumbbell/
    - assets/exercises/forearms/wristRoller/
    - assets/exercises/hamstrings/legCurlProne/
    - assets/exercises/hamstrings/legCurlSeated/
    - assets/exercises/hamstrings/romanianDeadlift/
    - assets/exercises/hamstrings/romanianDeadliftDumbbell/
    - assets/exercises/hips/clamshells/
    - assets/exercises/hips/gluteBridge/
    - assets/exercises/hips/hipAbduction/
    - assets/exercises/hips/hipAdduction/
    - assets/exercises/hips/hipThrust/
    - assets/exercises/hips/hipThrustBarbell/
    - assets/exercises/quadriceps/bodyweightSquats/
    - assets/exercises/quadriceps/bulgarianSplitSquats/
    - assets/exercises/quadriceps/frontSquats/
    - assets/exercises/quadriceps/legExtension/
    - assets/exercises/quadriceps/legPress/
    - assets/exercises/quadriceps/legPress45deg/
    - assets/exercises/quadriceps/lunges/
    - assets/exercises/quadriceps/smithMachineLunges/
    - assets/exercises/quadriceps/squatsBarbell/
    - assets/exercises/shoulders/arnoldPress/
    - assets/exercises/shoulders/bentOverLateralRaises/
    - assets/exercises/shoulders/frontDumbbellRaise/
    - assets/exercises/shoulders/handstandPushUps/
    - assets/exercises/shoulders/latRaisesCable/
    - assets/exercises/shoulders/latRaisesDualCable/
    - assets/exercises/shoulders/latRaisesInclinedBench/
    - assets/exercises/shoulders/pikePushUps/
    - assets/exercises/shoulders/reverseFlysInclinedBench/
    - assets/exercises/shoulders/shoulderPressMachine/
    - assets/exercises/shoulders/uprightRow/
    - assets/exercises/triceps/benchDips/
    - assets/exercises/triceps/diamondPushUps/
    - assets/exercises/triceps/dips/
    - assets/exercises/triceps/overheadRopeTricepExtension/
    - assets/exercises/triceps/skullCrushers/
    - assets/exercises/triceps/tricepKickbacks/
    - assets/exercises/triceps/tricepsMachine/
    - assets/exercises/triceps/tricepsRopePushdown/
    #tool end exercise-explanations
