name: gymtracker
description: A new Flutter project.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animations: ^2.0.7
  copy_with_extension: ^5.0.0
  device_info_plus: ^8.2.2
  device_sim: ^0.1.2
  dynamic_color: ^1.6.2
  file_picker: ^5.2.10
  fl_chart: ^0.61.0
  flat: ^0.5.0
  flex_color_picker: ^3.3.0
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^1.7.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.10.2
  flutter_slidable: ^2.0.0
  flutter_sticky_header: ^0.6.5
  flutter_timezone: ^1.0.8
  get: ^4.6.5
  get_storage: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_ui: ^1.0.14
  intl: ^0.18.0
  json_annotation: ^4.8.0
  package_info_plus: ^3.1.2
  protocol_handler: ^0.1.5
  share_plus: ^6.3.1
  timezone: ^0.9.2
  universal_platform: ^1.0.0+1
  uuid: ^3.0.7
  wolt_modal_sheet: ^0.4.1
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.yml
    - assets/i18n/it.yml