// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class FlutterCommunicatorPigeonCodecReader: FlutterStandardReader {
}

private class FlutterCommunicatorPigeonCodecWriter: FlutterStandardWriter {
}

private class FlutterCommunicatorPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterCommunicatorPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterCommunicatorPigeonCodecWriter(data: data)
  }
}

class FlutterCommunicatorPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterCommunicatorPigeonCodec(readerWriter: FlutterCommunicatorPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GymBroNativeHostAPI {
  func startWorkout() throws
  func stopWorkout() throws
  func setExerciseParameters(parameters: [String?: Any?]) throws
  func updateHomeWidgetParameters(parameters: [String: Int64], workoutDensityChartData: [Int64]) throws
  func requestHealthPermission() throws
  func updateFoodParameters(parameters: [String?: Any?]) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GymBroNativeHostAPISetup {
  static var codec: FlutterStandardMessageCodec { FlutterCommunicatorPigeonCodec.shared }
  /// Sets up an instance of `GymBroNativeHostAPI` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GymBroNativeHostAPI?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startWorkoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gymtracker.GymBroNativeHostAPI.startWorkout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startWorkoutChannel.setMessageHandler { _, reply in
        do {
          try api.startWorkout()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startWorkoutChannel.setMessageHandler(nil)
    }
    let stopWorkoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gymtracker.GymBroNativeHostAPI.stopWorkout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopWorkoutChannel.setMessageHandler { _, reply in
        do {
          try api.stopWorkout()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopWorkoutChannel.setMessageHandler(nil)
    }
    let setExerciseParametersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gymtracker.GymBroNativeHostAPI.setExerciseParameters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setExerciseParametersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! [String?: Any?]
        do {
          try api.setExerciseParameters(parameters: parametersArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setExerciseParametersChannel.setMessageHandler(nil)
    }
    let updateHomeWidgetParametersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gymtracker.GymBroNativeHostAPI.updateHomeWidgetParameters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateHomeWidgetParametersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! [String: Int64]
        let workoutDensityChartDataArg = args[1] as! [Int64]
        do {
          try api.updateHomeWidgetParameters(parameters: parametersArg, workoutDensityChartData: workoutDensityChartDataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateHomeWidgetParametersChannel.setMessageHandler(nil)
    }
    let requestHealthPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gymtracker.GymBroNativeHostAPI.requestHealthPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestHealthPermissionChannel.setMessageHandler { _, reply in
        do {
          try api.requestHealthPermission()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestHealthPermissionChannel.setMessageHandler(nil)
    }
    let updateFoodParametersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gymtracker.GymBroNativeHostAPI.updateFoodParameters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateFoodParametersChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let parametersArg = args[0] as! [String?: Any?]
        do {
          try api.updateFoodParameters(parameters: parametersArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateFoodParametersChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol GymBroNativeFlutterAPIProtocol {
  func markThisSetAsDone(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func requestTrainingData(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func handleWorkoutMetrics(energy energyArg: Double?, heartRate heartRateArg: Double?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func updateSetParameters(weight weightArg: Double?, timeSeconds timeSecondsArg: Double?, reps repsArg: Int64?, distance distanceArg: Double?, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class GymBroNativeFlutterAPI: GymBroNativeFlutterAPIProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FlutterCommunicatorPigeonCodec {
    return FlutterCommunicatorPigeonCodec.shared
  }
  func markThisSetAsDone(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.gymtracker.GymBroNativeFlutterAPI.markThisSetAsDone\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func requestTrainingData(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.gymtracker.GymBroNativeFlutterAPI.requestTrainingData\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func handleWorkoutMetrics(energy energyArg: Double?, heartRate heartRateArg: Double?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.gymtracker.GymBroNativeFlutterAPI.handleWorkoutMetrics\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([energyArg, heartRateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func updateSetParameters(weight weightArg: Double?, timeSeconds timeSecondsArg: Double?, reps repsArg: Int64?, distance distanceArg: Double?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.gymtracker.GymBroNativeFlutterAPI.updateSetParameters\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([weightArg, timeSecondsArg, repsArg, distanceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol GymBroNativeLoggerChannelProtocol {
  func logMessage(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func logError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class GymBroNativeLoggerChannel: GymBroNativeLoggerChannelProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FlutterCommunicatorPigeonCodec {
    return FlutterCommunicatorPigeonCodec.shared
  }
  func logMessage(message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.gymtracker.GymBroNativeLoggerChannel.logMessage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func logError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.gymtracker.GymBroNativeLoggerChannel.logError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
