name: Integration tests

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: "stable"
          cache: true

      - run: flutter pub get

      # Build the app before running the integration tests
      # This is apparently necessary for the integration tests to work
      # without timing out
      - name: Build
        run: flutter build macos

      - run: flutter test integration_test -d macos
