name: Unit tests
on:
  push:
    branches:
      - '**'
  pull_request: {}

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"
      - name: Get Flutter packages
        run: flutter pub get
      - name: Build env
        env:
          DOTENV: ${{ secrets.DOTENV }}
        run: |
          echo $DOTENV > .env
          set -a; source .env; set +a
          dart run build_runner clean && dart run build_runner build --delete-conflicting-outputs
      - name: Run Flutter tests
        run: flutter test